cube1 = ['a','a','a','f','r','s']
cube2 = ['a','a','e','e','e','e']
cube3 = ['a','a','f','i','r','s']
cube4 = ['a','d','e','n','n','n']
cube5 = ['a','e','e','e','e','m']

cube6 = ['a','e','e','g','m','u']
cube7 = ['a','e','g','m','n','n']
cube8 = ['a','f','i','r','s','y']
cube9 = ['b','j','k','q','x','z']
cube10 = ['c','c','e','n','s','t']

cube11 = ['c','e','i','i','l','t']
cube12 = ['c','e','i','l','p','t']
cube13 = ['c','e','i','p','s','t']
cube14 = ['d','d','h','n','o','t']
cube15 = ['d','h','h','l','o','r']

cube16 = ['d','h','l','n','o','r']
cube17 = ['d','h','l','n','o','r']
cube18 = ['e','i','i','i','t','t']
cube19 = ['e','m','o','t','t','t']
cube20 = ['e','n','s','s','s','u']

cube21 = ['f','i','p','r','s','y']
cube22 = ['g','o','r','r','v','w']
cube23 = ['i','p','r','r','r','y']
cube24 = ['n','o','o','t','u','w']
cube25 = ['o','o','o','t','t','u']

diceArray5x5 = [cube1, cube2, cube3, cube4, cube5, cube6, cube7, cube8, cube9, cube10, cube11, cube12, cube13,cube14,
             cube15, cube16, cube17, cube18, cube19, cube20, cube21, cube22, cube23, cube24, cube25]

die1 = ['A','A','C','I','O','T']
die2 = ['A','B','I','L','T','Y']
die3 = ['A','B','J','M','O','Q']
die4= ['A','C','D','E','M','P']
die5= ['A','C','E','L','R','S']
die6= ['A','D','E','N','V','Z']
die7= ['A','H','M','O','R','S']
die8= ['B','I','F','O','R','X']
die9= ['D','E','N','O','S','W']
die10= ['D','K','N','O','T','U']
die11= ['E','E','F','H','I','Y']
die12= ['E','G','K','L','U','Y']
die13= ['E','G','I','N','T','V']
die14= ['E','H','I','N','P','S']
die15= ['E','L','P','S','T','U']
die16= ['G','I','L','R','U','W']

diceArray4x4 = [die1, die2, die3, die4, die5, die6, die7, die8, die9, die10, die11, die12, die13, die14, die15, die16]
